---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
stringData:
  postgres_password: synapse
  init.sql: |
      CREATE USER synapse_user WITH PASSWORD 'synapse';
      CREATE DATABASE synapse WITH OWNER = 'synapse_user' TEMPLATE = 'template0' ENCODING = 'utf-8' LC_COLLATE = 'C' LC_CTYPE = 'C';
