---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
      appProtocol: tcp
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: matrix
